# -*- coding: utf-8 -*-
"""weblog_kmean.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DwcFt1DgsesyEAxfiAOVTNvXU-189J_2
"""

import pandas as pd

dataset = pd.read_csv('weblog1.csv')

dataset=dataset.dropna()

dataset=dataset[['IP', 'Staus']]

dataset=dataset.groupby(['IP', 'Staus']).Staus.agg('count').to_frame('Count').reset_index()

traindata=dataset.drop(['IP'],axis=1)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

data_scaled = sc.fit_transform(traindata)



from sklearn.cluster import KMeans

model=KMeans(n_clusters=4)

pred=model.fit_predict(data_scaled)



finaldataset=dataset

finaldataset["Cluster"]=pred





#import plotly.express as px

#fig = px.scatter(finaldataset,'Staus','Count','Cluster',hover_data=['IP'])

#fig.show()

a=[]
for index, row in dataset.iterrows(): 
    if row['Staus'] > 200:
       a.append(row['Cluster'])

blockedCluster = max(set(a), key = a.count)



blockedIP=[]

for index, row in dataset.iterrows(): 
    if row['Cluster'] == blockedCluster:
       blockedIP.append(row['IP'])

blockedIP=set(blockedIP)



with open('blockedIp.txt', 'w') as filehandle:
    for listitem in blockedIP:
        filehandle.write('%s\n' % listitem)

